### ISSUE TITLE
Personal Pages

### ISSUE THREAD

**Issue by thevangelist** [Lepovirta/lepovirta.org#6]
Add minimalistic personal pages for all developers.

**Comment by jkpl** [comment]
How about something like this?

* The front page lists the devs
* Each dev has a couple of lines of description about them, and links to their works.
* In the bottom of the description there could be link "more about xxx". The link leads to dev's personal homepage which is maintained separately from lepovirta.org.

I can provide Lepovirta sub domains for personal homepages.

**Comment by keveri** [comment]
This is a bit related to Blog issue #7 if/when blogs are located on personal pages.

**Comment by keveri** [comment]
+1 for small description and link to personal site. Then there is no need to update info on multiple places if it changes.

**Comment by thevangelist** [comment]
One thing we discussed with @Jkpl is unified, minimalistic look with a possibly centered styling. i.e. avatar on top and links / description below it. The idea would be that there's some unified elements on page + a custom area for carmageddon.

**Comment by jkpl** [comment]
Continuing development in Lepovirta/lepo#2
