### ISSUE TITLE
Blog?

### ISSUE THREAD

**Issue by thevangelist** [Lepovirta/lepovirta.org#7]
Do we want to blog?

**Comment by thevangelist** [comment]
Blog could be implemented while & with the static site generator.. and posts written in markdown

**Comment by jkpl** [comment]
Another choice would be to maintain an aggregation of posts from devs' personal blogs.

**Comment by keveri** [comment]
Some kind of RSS feed aggregation from personal blogs might be good if it's easy to maintain.

**Comment by jkpl** [comment]
It should be pretty easy to create a script which updates an RSS feed and a web page based on other RSS feeds. How it would be automated is a different business thou. OTOH, I'm not sure if we even need to automate it.

**Comment by keveri** [comment]
script should be enough

**Comment by jkpl** [comment]
There's gonna be a blog in the new site.
